config/routes.rb
Rails.application.routes.draw do
  resources :videos

  resources :play_infos

  resources :hosts

  resources :hams

  resources :crawlers

  resources :clients

  resources :cars

  resources :buildings

end

app/models/ham.rb
class Ham < ActiveRecord::Base
end

app/controllers/hams_controller.rb
class HamsController < ApplicationController
  before_action :set_ham, only: [:show, :edit, :update, :destroy]

  # GET /hams
  # GET /hams.json
  def index
    @hams = Ham.all
  end

  # GET /hams/1
  # GET /hams/1.json
  def show
  end

  # GET /hams/new
  def new
    @ham = Ham.new
  end

  # GET /hams/1/edit
  def edit
  end

  # POST /hams
  # POST /hams.json
  def create
    @ham = Ham.new(ham_params)

    respond_to do |format|
      if @ham.save
        format.html { redirect_to @ham, notice: 'Ham was successfully created.' }
        format.json { render :show, status: :created, location: @ham }
      else
        format.html { render :new }
        format.json { render json: @ham.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hams/1
  # PATCH/PUT /hams/1.json
  def update
    respond_to do |format|
      if @ham.update(ham_params)
        format.html { redirect_to @ham, notice: 'Ham was successfully updated.' }
        format.json { render :show, status: :ok, location: @ham }
      else
        format.html { render :edit }
        format.json { render json: @ham.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hams/1
  # DELETE /hams/1.json
  def destroy
    @ham.destroy
    respond_to do |format|
      format.html { redirect_to hams_url, notice: 'Ham was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ham
      @ham = Ham.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ham_params
      params[:ham]
    end
end

app/helpers/hams_helper.rb
module HamsHelper
end

app/views/hams/_form.html.erb
<%= form_for(@ham) do |f| %>
  <% if @ham.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ham.errors.count, "error") %> prohibited this ham from being saved:</h2>

      <ul>
      <% @ham.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hams/edit.html.erb
<h1>Editing ham</h1>

<%= render 'form' %>

<%= link_to 'Show', @ham %> |
<%= link_to 'Back', hams_path %>

app/views/hams/index.html.erb
<h1>Listing hams</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hams.each do |ham| %>
      <tr>
        <td><%= link_to 'Show', ham %></td>
        <td><%= link_to 'Edit', edit_ham_path(ham) %></td>
        <td><%= link_to 'Destroy', ham, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ham', new_ham_path %>

app/views/hams/new.html.erb
<h1>New ham</h1>

<%= render 'form' %>

<%= link_to 'Back', hams_path %>

app/views/hams/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ham_path(@ham) %> |
<%= link_to 'Back', hams_path %>